{% set pytest_args = "--cov-fail-under=59 -k \"not (multilevel_modules_on_physical or multilevel_modules_states or precomputed)\"" %}
{% set pytest_args = '--cov-fail-under=59 -k "not (multilevel_modules_on_physical or multilevel_modules_states or precomputed)"' %}
{% set version = "2.8.0" %}

package:
  name: python-infomap
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/i/infomap/infomap-{{ version }}.tar.gz
    sha256: 17eff0882afa5de9bf68f2fba013b06be43d618191859e6723e008e744944e36
  - folder: src
    url: https://github.com/mapequation/infomap/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 592c5d0fb355fe716d33cfe11d038d9cd0bc57cb8633efcded03191365efb184

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - infomap = infomap:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("c") }}    # [win]
    - llvm-openmp     # [osx]
    - libgomp         # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - src/test
    - src/examples/networks
  requires:
    - pip
    - pytest-cov
  imports:
    - infomap
  commands:
    - pip check
    - infomap --version
    - infomap --help
    - cd src && pytest --cov=infomap --cov=branch --cov-report=term-missing:skip-covered --no-cov-on-fail {{ pytest_args }}

about:
  home: https://www.mapequation.org/infomap
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: dist/LICENSE
  summary: Infomap network clustering algorithm
  doc_url: https://mapequation.github.io/infomap/python
  dev_url: https://github.com/mapequation/infomap/tree/master/interfaces/python

extra:
  recipe-maintainers:
    - bollwyvl
