# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.9.2"

package:
  name: python-infomap
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/i/infomap/infomap-${{ version }}.tar.gz
    sha256: e0c61ded3531bcff019a024d6e37396e920db9ffdf43a6caca0b68b71e404036
    target_directory: dist
    patches:
      - if: win
        then: 0000-no-win-clang.patch
  - url: https://github.com/mapequation/infomap/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 2a94f10dd3974ebb2b5ffabae5c018b928e10926cb9b3d9ba77f5416e0a7c392
    target_directory: src

build:
  number: 0
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - infomap = infomap:main

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - if: osx
      then:
        - llvm-openmp
    - if: linux
      then:
        - libgomp
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports: infomap
      pip_check: true
  - files:
      source:
        - src/test/
        - src/examples/networks/
    requirements:
      run:
        - pytest-cov
    script:
      - infomap --version
      - infomap --help
      - cd src
      - coverage run --source=infomap --branch -m pytest -vv --tb=long --color=yes -k "not (multilevel_modules_on_physical or multilevel_modules_states or precomputed)"
      - coverage report --show-missing --skip-covered --fail-under=56

about:
  license: GPL-3.0-or-later
  license_file: dist/LICENSE
  summary: Infomap network clustering algorithm
  homepage: https://www.mapequation.org/infomap
  repository: https://github.com/mapequation/infomap/tree/master/interfaces/python
  documentation: https://mapequation.github.io/infomap/python

extra:
  recipe-maintainers:
    - bollwyvl
