# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.11.0"

package:
  name: python-infomap
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/i/infomap/infomap-${{ version }}.tar.gz
    sha256: d6eea9e97fd808c8c300ba563b8f1594a3f937185a7c0bf4573e9dc20815c46a
    target_directory: dist
    patches:
      - if: win
        then: 0000-no-win-clang.patch
  - url: https://github.com/mapequation/infomap/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 1f9906183db317889e8862524e8317505196f46047b3a3fbe4672b8b89dde2d1
    target_directory: src

build:
  number: 0
  skip: match(python, "<3.11")
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - infomap = infomap:main

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: osx
      then:
        - llvm-openmp
    - if: linux
      then:
        - libgomp
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports: infomap
      pip_check: true
  - files:
      source:
        - src/examples/networks/
        - src/pyproject.toml
        - src/scripts/benchmarks/
        - src/scripts/build_config.py
        - src/test/
    requirements:
      run:
        - networkx
        - numpy
        - pytest-cov
    script:
      - infomap --version
      - infomap --help
      - cd src
      - coverage run --source=infomap --branch -m pytest -vv --tb=long --color=yes -k "not (multilevel_modules_on_physical or multilevel_modules_states or precomputed)"
      - coverage report --show-missing --skip-covered --fail-under=64

about:
  license: GPL-3.0-or-later
  license_file: dist/LICENSE_GPLv3.txt
  summary: Infomap network clustering algorithm
  homepage: https://www.mapequation.org/infomap
  repository: https://github.com/mapequation/infomap/tree/master/interfaces/python
  documentation: https://mapequation.github.io/infomap/python

extra:
  recipe-maintainers:
    - bollwyvl
